# client/Dockerfile
FROM node:18

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# Use static file server for final app
RUN npm install -g serve
EXPOSE 4173
CMD ["serve", "-s", "dist"]
